### ISSUE TITLE
erro NullPointerException

### ISSUE THREAD

**Issue by jr3074** [whyorean/aurora-dispenser#3]
OS ubuntu 18.04

success to build but get error while running the jar file

Exception in thread "main" java.lang.NullPointerException
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:149)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.base/java.io.FileReader.<init>(FileReader.java:60)
        at com.aurora.store.tokendispenser.Server.main(Server.java:25)

**Comment by whyorean** [comment]
Make sure you have the required files present in the required folder, as stated in README

**Comment by choccy** [comment]
@whyorean Where is the auth.txt file supposed to be stored? It's not mentioned in the README afaik
